/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user;

import config.Session;
import config.dbConnector;
import config.passwordHasher;
import java.awt.Color;
import java.security.NoSuchAlgorithmException;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import myapp.loginForm;

/**
 *
 * @author cedricjadee
 */
public class userChangepass extends javax.swing.JInternalFrame {

    /**
     * Creates new form userChangepass
     */
    public userChangepass() {
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
    }
    
        Color hover = new Color(0,0,0);
        Color button = new Color (0,51,51);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        changePass = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        changePass1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        oldpass = new javax.swing.JPasswordField();
        newpass = new javax.swing.JPasswordField();
        conpass = new javax.swing.JPasswordField();

        changePass.setBackground(new java.awt.Color(0, 51, 51));
        changePass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changePassMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                changePassMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                changePassMouseExited(evt);
            }
        });
        changePass.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("SAVE");
        changePass.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 190, 28));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(659, 420));
        jPanel1.setPreferredSize(new java.awt.Dimension(659, 420));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("CHANGE PASSWORD");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 20));

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 80, 10));

        changePass1.setBackground(new java.awt.Color(0, 51, 51));
        changePass1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changePass1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                changePass1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                changePass1MouseExited(evt);
            }
        });
        changePass1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("SAVE");
        changePass1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 140, 28));

        jPanel1.add(changePass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, 140, 50));

        id.setBackground(new java.awt.Color(0, 0, 0));
        id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        id.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "ID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        id.setEnabled(false);
        id.setOpaque(false);
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 280, 50));

        oldpass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        oldpass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        oldpass.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Old Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        oldpass.setOpaque(false);
        jPanel1.add(oldpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 280, 50));

        newpass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        newpass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        newpass.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "New Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        newpass.setOpaque(false);
        jPanel1.add(newpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 280, 50));

        conpass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        conpass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        conpass.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Confirm Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        conpass.setOpaque(false);
        jPanel1.add(conpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 280, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changePassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePassMouseClicked

    }//GEN-LAST:event_changePassMouseClicked

    private void changePassMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePassMouseEntered
       
    }//GEN-LAST:event_changePassMouseEntered

    private void changePassMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePassMouseExited
      
    }//GEN-LAST:event_changePassMouseExited

    private void changePass1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePass1MouseClicked

        try{
            dbConnector dbc = new dbConnector();
            Session sess = Session.getInstance();

            String query = "SELECT * FROM tbl_user WHERE u_id= '"+sess.getUid()+"'";
            ResultSet rs = dbc.getData(query);

            if(rs.next()){
                String olddbpass = rs.getString("u_password");
                String oldhash = passwordHasher.hashPassword(oldpass.getText());

                if(!olddbpass.equals(oldhash)){
                    JOptionPane.showMessageDialog(null, "Old Password is Incorrect!");
                    oldpass.setText("");
                }else if(newpass.getText().length() < 8){
                    JOptionPane.showMessageDialog(null, "Password must be 8 characters and above!");
                    newpass.setText("");
                }else if(!newpass.getText().equals(conpass.getText())){
                    JOptionPane.showMessageDialog(null, "Confirm Password does not Match!");
                    conpass.setText("");
                }else{
                    String npass = passwordHasher.hashPassword(newpass.getText());
                    dbc.updateData("UPDATE tbl_user SET u_password = '"+npass+"' WHERE u_id = '"+sess.getUid()+"'");
                    JOptionPane.showMessageDialog(null, "Password Changed Successfully!");
                    loginForm lf = new loginForm();
                    lf.setVisible(true);
                    this.dispose();
                }
            }

        }catch(SQLException | NoSuchAlgorithmException ex){
            System.out.println(""+ex);
        }
    }//GEN-LAST:event_changePass1MouseClicked

    private void changePass1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePass1MouseEntered
        changePass1.setBackground(hover);
    }//GEN-LAST:event_changePass1MouseEntered

    private void changePass1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePass1MouseExited
        changePass1.setBackground(button);
    }//GEN-LAST:event_changePass1MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel changePass;
    private javax.swing.JPanel changePass1;
    public javax.swing.JPasswordField conpass;
    public javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JPasswordField newpass;
    public javax.swing.JPasswordField oldpass;
    // End of variables declaration//GEN-END:variables
}
